# -*- coding: utf-8 -*-
"""Data_Generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CshmkRV-Ck_IwyPPxx3fz6IIA3XgGMXZ
"""

!pip install Faker

"""
Operational Asset & Work Order Analytics
Stage 1: Generate ~500 rows of realistic maintenance data into SQLite
"""

import sqlite3
import random
from datetime import datetime, timedelta
from faker import Faker

fake = Faker()
random.seed(42)
Faker.seed(42)

DB_PATH = "/content/maintenance.db"

# ─────────────────────────────────────────────
# 1. SCHEMA
# ─────────────────────────────────────────────

SCHEMA = """
-- Assets being maintained (aircraft, GSE, vehicles, machinery)
CREATE TABLE IF NOT EXISTS assets (
    asset_id        TEXT PRIMARY KEY,
    asset_name      TEXT NOT NULL,
    asset_type      TEXT NOT NULL,       -- Aircraft, GSE, Vehicle, Machinery
    location        TEXT NOT NULL,       -- Hangar A, Hangar B, Apron, Workshop
    manufacturer    TEXT NOT NULL,
    model           TEXT NOT NULL,
    purchase_year   INTEGER NOT NULL,
    status          TEXT NOT NULL        -- Active, Inactive, Under Maintenance
);

-- Technicians who carry out work orders
CREATE TABLE IF NOT EXISTS technicians (
    technician_id   TEXT PRIMARY KEY,
    full_name       TEXT NOT NULL,
    skill_level     TEXT NOT NULL,       -- Junior, Senior, Lead
    specialisation  TEXT NOT NULL,       -- Avionics, Mechanical, Hydraulics, Electrical
    hourly_rate     REAL NOT NULL,
    active          INTEGER NOT NULL DEFAULT 1
);

-- SLA targets: how quickly each priority must be resolved
CREATE TABLE IF NOT EXISTS sla_definitions (
    priority        TEXT PRIMARY KEY,    -- Critical, High, Medium, Low
    target_hours    REAL NOT NULL,       -- Max hours to close after creation
    escalation_hours REAL NOT NULL       -- Hours before escalation warning
);

-- Core work order table
CREATE TABLE IF NOT EXISTS work_orders (
    wo_id               TEXT PRIMARY KEY,
    asset_id            TEXT NOT NULL REFERENCES assets(asset_id),
    technician_id       TEXT REFERENCES technicians(technician_id),
    wo_type             TEXT NOT NULL,   -- Preventive, Corrective, Inspection, Emergency
    priority            TEXT NOT NULL REFERENCES sla_definitions(priority),
    status              TEXT NOT NULL,   -- Open, In Progress, Completed, Cancelled
    description         TEXT NOT NULL,
    created_at          TEXT NOT NULL,
    started_at          TEXT,
    completed_at        TEXT,
    downtime_hours      REAL,            -- Asset downtime caused by this WO
    failure_code        TEXT             -- e.g. HYD-001, ELE-002
);

-- Parts and labour costs per work order
CREATE TABLE IF NOT EXISTS work_order_costs (
    cost_id         INTEGER PRIMARY KEY AUTOINCREMENT,
    wo_id           TEXT NOT NULL REFERENCES work_orders(wo_id),
    cost_type       TEXT NOT NULL,       -- Parts, Labour, Subcontract
    description     TEXT NOT NULL,
    amount          REAL NOT NULL,
    currency        TEXT NOT NULL DEFAULT 'USD'
);
"""

# ─────────────────────────────────────────────
# 2. REFERENCE DATA
# ─────────────────────────────────────────────

ASSET_TYPES   = ["Aircraft", "GSE", "Vehicle", "Machinery"]
LOCATIONS     = ["Hangar A", "Hangar B", "Apron", "Workshop", "Remote Bay"]
MANUFACTURERS = {
    "Aircraft":  ["Boeing", "Airbus", "Embraer"],
    "GSE":       ["JBT", "Tronair", "Charlatte"],
    "Vehicle":   ["Toyota", "Ford", "Volvo"],
    "Machinery": ["Caterpillar", "Komatsu", "Atlas Copco"],
}
MODELS = {
    "Aircraft":  ["737-800", "A320neo", "E175", "777-300ER", "A350-900"],
    "GSE":       ["Jetway X1", "Power Unit 400A", "Belt Loader BL5", "GPU-90"],
    "Vehicle":   ["Land Cruiser", "Transit Van", "FM 410"],
    "Machinery": ["D6T Dozer", "PC210 Excavator", "XAS 185"],
}
SPECIALISATIONS = ["Avionics", "Mechanical", "Hydraulics", "Electrical", "Structures"]
SKILL_LEVELS    = ["Junior", "Senior", "Lead"]
HOURLY_RATES    = {"Junior": 35.0, "Senior": 60.0, "Lead": 90.0}

WO_TYPES      = ["Preventive", "Corrective", "Inspection", "Emergency"]
PRIORITIES    = ["Critical", "High", "Medium", "Low"]
STATUSES      = ["Open", "In Progress", "Completed", "Cancelled"]
FAILURE_CODES = [
    "HYD-001", "HYD-002", "ELE-001", "ELE-002", "ELE-003",
    "MEC-001", "MEC-002", "AVN-001", "STR-001", "STR-002",
    None, None, None  # Many WOs won't have a failure code
]
WO_DESCRIPTIONS = {
    "Preventive":  ["Scheduled 500-hr inspection", "Lubrication service", "Filter replacement", "Torque check"],
    "Corrective":  ["Hydraulic leak repair", "Electrical fault trace", "Landing gear snag", "Engine vibration fix"],
    "Inspection":  ["Pre-flight walkaround", "Borescope inspection", "NDT check", "Annual compliance check"],
    "Emergency":   ["AOG engine fault", "Emergency hydraulic failure", "Critical avionics failure", "Fire warning system fault"],
}

SLA_TARGETS = {
    "Critical": (4.0,  2.0),
    "High":     (24.0, 12.0),
    "Medium":   (72.0, 48.0),
    "Low":      (168.0, 120.0),
}

COST_DESCRIPTIONS = {
    "Parts":       ["Hydraulic seal kit", "Filter element", "Wiring harness", "Bearing assembly", "Actuator unit"],
    "Labour":      ["Technician hours", "Specialist call-out", "Overtime labour"],
    "Subcontract": ["OEM engineering visit", "Third-party NDT", "Avionics shop repair"],
}

# ─────────────────────────────────────────────
# 3. GENERATE DATA
# ─────────────────────────────────────────────

def gen_assets(n=30):
    rows = []
    for i in range(1, n + 1):
        atype = random.choice(ASSET_TYPES)
        mfr   = random.choice(MANUFACTURERS[atype])
        model = random.choice(MODELS[atype])
        rows.append((
            f"AST-{i:04d}",
            f"{mfr} {model} #{i:03d}",
            atype,
            random.choice(LOCATIONS),
            mfr,
            model,
            random.randint(2010, 2022),
            random.choices(["Active", "Inactive", "Under Maintenance"], weights=[70, 10, 20])[0],
        ))
    return rows

def gen_technicians(n=20):
    rows = []
    for i in range(1, n + 1):
        level = random.choice(SKILL_LEVELS)
        rows.append((
            f"TECH-{i:04d}",
            fake.name(),
            level,
            random.choice(SPECIALISATIONS),
            HOURLY_RATES[level] + random.uniform(-5, 10),
            1,
        ))
    return rows

def gen_work_orders(assets, technicians, n=500):
    rows = []
    base_date = datetime(2023, 1, 1)
    asset_ids = [a[0] for a in assets]
    tech_ids  = [t[0] for t in technicians]

    for i in range(1, n + 1):
        wo_type  = random.choices(WO_TYPES, weights=[35, 35, 20, 10])[0]
        priority = random.choices(PRIORITIES, weights=[10, 25, 40, 25])[0]
        status   = random.choices(STATUSES, weights=[10, 15, 70, 5])[0]

        created_at = base_date + timedelta(
            days=random.randint(0, 364),
            hours=random.randint(6, 20)
        )

        started_at = completed_at = None
        downtime_hours = None

        if status in ("In Progress", "Completed", "Cancelled"):
            started_at = created_at + timedelta(hours=random.uniform(0.5, 8))

        if status == "Completed":
            target_h = SLA_TARGETS[priority][0]
            # ~75% of WOs meet SLA
            if random.random() < 0.75:
                duration = random.uniform(target_h * 0.2, target_h * 0.95)
            else:
                duration = random.uniform(target_h * 1.0, target_h * 2.5)
            completed_at = started_at + timedelta(hours=duration)
            downtime_hours = round(random.uniform(0, duration * 0.8), 2)

        rows.append((
            f"WO-{i:05d}",
            random.choice(asset_ids),
            random.choice(tech_ids) if status != "Open" else None,
            wo_type,
            priority,
            status,
            random.choice(WO_DESCRIPTIONS[wo_type]),
            created_at.strftime("%Y-%m-%d %H:%M:%S"),
            started_at.strftime("%Y-%m-%d %H:%M:%S") if started_at else None,
            completed_at.strftime("%Y-%m-%d %H:%M:%S") if completed_at else None,
            downtime_hours,
            random.choice(FAILURE_CODES) if wo_type in ("Corrective", "Emergency") else None,
        ))
    return rows

def gen_costs(work_orders):
    rows = []
    for wo in work_orders:
        wo_id  = wo[0]
        status = wo[5]
        if status not in ("Completed", "In Progress"):
            continue
        # 1–3 cost lines per eligible WO
        for _ in range(random.randint(1, 3)):
            ctype = random.choices(
                ["Parts", "Labour", "Subcontract"], weights=[50, 40, 10]
            )[0]
            rows.append((
                wo_id,
                ctype,
                random.choice(COST_DESCRIPTIONS[ctype]),
                round(random.uniform(50, 4500) if ctype == "Parts"
                      else random.uniform(100, 2000) if ctype == "Labour"
                      else random.uniform(500, 8000), 2),
                "USD",
            ))
    return rows

# ─────────────────────────────────────────────
# 4. WRITE TO SQLITE
# ─────────────────────────────────────────────

def build_database():
    conn = sqlite3.connect(DB_PATH)
    cur  = conn.cursor()
    cur.executescript(SCHEMA)

    # SLA definitions
    for priority, (target, escalation) in SLA_TARGETS.items():
        cur.execute(
            "INSERT OR IGNORE INTO sla_definitions VALUES (?,?,?)",
            (priority, target, escalation)
        )

    assets      = gen_assets(30)
    technicians = gen_technicians(20)
    work_orders = gen_work_orders(assets, technicians, 500)
    costs       = gen_costs(work_orders)

    cur.executemany("INSERT OR IGNORE INTO assets VALUES (?,?,?,?,?,?,?,?)", assets)
    cur.executemany("INSERT OR IGNORE INTO technicians VALUES (?,?,?,?,?,?)", technicians)
    cur.executemany("INSERT OR IGNORE INTO work_orders VALUES (?,?,?,?,?,?,?,?,?,?,?,?)", work_orders)
    cur.executemany(
        "INSERT INTO work_order_costs (wo_id,cost_type,description,amount,currency) VALUES (?,?,?,?,?)",
        costs
    )

    conn.commit()

    # ── Summary ──────────────────────────────
    print("✅  Database built:", DB_PATH)
    for table in ["assets", "technicians", "sla_definitions", "work_orders", "work_order_costs"]:
        count = cur.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
        print(f"   {table:<22} {count:>5} rows")

    # Quick sanity checks
    print("\n── SLA compliance preview ──")
    cur.execute("""
        SELECT
            wo.priority,
            COUNT(*) AS total,
            SUM(CASE
                WHEN (julianday(wo.completed_at) - julianday(wo.created_at)) * 24
                     <= sla.target_hours THEN 1 ELSE 0
            END) AS met,
            ROUND(
                100.0 * SUM(CASE
                    WHEN (julianday(wo.completed_at) - julianday(wo.created_at)) * 24
                         <= sla.target_hours THEN 1 ELSE 0
                END) / COUNT(*), 1
            ) AS pct
        FROM work_orders wo
        JOIN sla_definitions sla ON wo.priority = sla.priority
        WHERE wo.status = 'Completed'
        GROUP BY wo.priority
        ORDER BY CASE wo.priority
            WHEN 'Critical' THEN 1 WHEN 'High' THEN 2
            WHEN 'Medium' THEN 3 ELSE 4 END
    """)
    print(f"   {'Priority':<10} {'Total':>6} {'Met SLA':>8} {'%':>6}")
    for row in cur.fetchall():
        print(f"   {row[0]:<10} {row[1]:>6} {row[2]:>8} {row[3]:>5}%")

    print("\n── Total cost by type ──")
    cur.execute("""
        SELECT cost_type, COUNT(*), ROUND(SUM(amount),2)
        FROM work_order_costs GROUP BY cost_type
    """)
    for row in cur.fetchall():
        print(f"   {row[0]:<14} {row[1]:>4} lines   ${row[2]:>10,.2f}")

    conn.close()

if __name__ == "__main__":
    build_database()

import sqlite3
conn = sqlite3.connect("/content/maintenance.db")
cur = conn.cursor()

# Get column names for work_orders
cur.execute("PRAGMA table_info(work_orders)")
print([row[1] for row in cur.fetchall()])

for table in ["assets", "technicians", "work_order_costs", "sla_definitions"]:
    cur.execute(f"PRAGMA table_info({table})")
    print(f"{table}: {[row[1] for row in cur.fetchall()]}")

import pandas as pd
import sqlite3

conn = sqlite3.connect("/content/maintenance.db")

tables = ["assets", "technicians", "work_orders", "work_order_costs", "sla_definitions"]

for table in tables:
    df = pd.read_sql_query(f"SELECT * FROM {table}", conn)
    df.to_csv(f"/content/{table}.csv", index=False)
    print(f"{table}: {len(df)} rows exported")

conn.close()

import os
for f in os.listdir("/content"):
    if f.endswith(".csv"):
        print(f)

