# -*- coding: utf-8 -*-
"""sql_queries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pKkqUa27-FhXHczoRAP_TLA0GclLSBBH
"""

!pip install Faker

"""
Operational Asset & Work Order Analytics
Stage 1: Generate ~500 rows of realistic maintenance data into SQLite
"""

import sqlite3
import random
from datetime import datetime, timedelta
from faker import Faker

fake = Faker()
random.seed(42)
Faker.seed(42)

DB_PATH = "/content/maintenance.db"

# ─────────────────────────────────────────────
# 1. SCHEMA
# ─────────────────────────────────────────────

SCHEMA = """
-- Assets being maintained (aircraft, GSE, vehicles, machinery)
CREATE TABLE IF NOT EXISTS assets (
    asset_id        TEXT PRIMARY KEY,
    asset_name      TEXT NOT NULL,
    asset_type      TEXT NOT NULL,       -- Aircraft, GSE, Vehicle, Machinery
    location        TEXT NOT NULL,       -- Hangar A, Hangar B, Apron, Workshop
    manufacturer    TEXT NOT NULL,
    model           TEXT NOT NULL,
    purchase_year   INTEGER NOT NULL,
    status          TEXT NOT NULL        -- Active, Inactive, Under Maintenance
);

-- Technicians who carry out work orders
CREATE TABLE IF NOT EXISTS technicians (
    technician_id   TEXT PRIMARY KEY,
    full_name       TEXT NOT NULL,
    skill_level     TEXT NOT NULL,       -- Junior, Senior, Lead
    specialisation  TEXT NOT NULL,       -- Avionics, Mechanical, Hydraulics, Electrical
    hourly_rate     REAL NOT NULL,
    active          INTEGER NOT NULL DEFAULT 1
);

-- SLA targets: how quickly each priority must be resolved
CREATE TABLE IF NOT EXISTS sla_definitions (
    priority        TEXT PRIMARY KEY,    -- Critical, High, Medium, Low
    target_hours    REAL NOT NULL,       -- Max hours to close after creation
    escalation_hours REAL NOT NULL       -- Hours before escalation warning
);

-- Core work order table
CREATE TABLE IF NOT EXISTS work_orders (
    wo_id               TEXT PRIMARY KEY,
    asset_id            TEXT NOT NULL REFERENCES assets(asset_id),
    technician_id       TEXT REFERENCES technicians(technician_id),
    wo_type             TEXT NOT NULL,   -- Preventive, Corrective, Inspection, Emergency
    priority            TEXT NOT NULL REFERENCES sla_definitions(priority),
    status              TEXT NOT NULL,   -- Open, In Progress, Completed, Cancelled
    description         TEXT NOT NULL,
    created_at          TEXT NOT NULL,
    started_at          TEXT,
    completed_at        TEXT,
    downtime_hours      REAL,            -- Asset downtime caused by this WO
    failure_code        TEXT             -- e.g. HYD-001, ELE-002
);

-- Parts and labour costs per work order
CREATE TABLE IF NOT EXISTS work_order_costs (
    cost_id         INTEGER PRIMARY KEY AUTOINCREMENT,
    wo_id           TEXT NOT NULL REFERENCES work_orders(wo_id),
    cost_type       TEXT NOT NULL,       -- Parts, Labour, Subcontract
    description     TEXT NOT NULL,
    amount          REAL NOT NULL,
    currency        TEXT NOT NULL DEFAULT 'USD'
);
"""

# ─────────────────────────────────────────────
# 2. REFERENCE DATA
# ─────────────────────────────────────────────

ASSET_TYPES   = ["Aircraft", "GSE", "Vehicle", "Machinery"]
LOCATIONS     = ["Hangar A", "Hangar B", "Apron", "Workshop", "Remote Bay"]
MANUFACTURERS = {
    "Aircraft":  ["Boeing", "Airbus", "Embraer"],
    "GSE":       ["JBT", "Tronair", "Charlatte"],
    "Vehicle":   ["Toyota", "Ford", "Volvo"],
    "Machinery": ["Caterpillar", "Komatsu", "Atlas Copco"],
}
MODELS = {
    "Aircraft":  ["737-800", "A320neo", "E175", "777-300ER", "A350-900"],
    "GSE":       ["Jetway X1", "Power Unit 400A", "Belt Loader BL5", "GPU-90"],
    "Vehicle":   ["Land Cruiser", "Transit Van", "FM 410"],
    "Machinery": ["D6T Dozer", "PC210 Excavator", "XAS 185"],
}
SPECIALISATIONS = ["Avionics", "Mechanical", "Hydraulics", "Electrical", "Structures"]
SKILL_LEVELS    = ["Junior", "Senior", "Lead"]
HOURLY_RATES    = {"Junior": 35.0, "Senior": 60.0, "Lead": 90.0}

WO_TYPES      = ["Preventive", "Corrective", "Inspection", "Emergency"]
PRIORITIES    = ["Critical", "High", "Medium", "Low"]
STATUSES      = ["Open", "In Progress", "Completed", "Cancelled"]
FAILURE_CODES = [
    "HYD-001", "HYD-002", "ELE-001", "ELE-002", "ELE-003",
    "MEC-001", "MEC-002", "AVN-001", "STR-001", "STR-002",
    None, None, None  # Many WOs won't have a failure code
]
WO_DESCRIPTIONS = {
    "Preventive":  ["Scheduled 500-hr inspection", "Lubrication service", "Filter replacement", "Torque check"],
    "Corrective":  ["Hydraulic leak repair", "Electrical fault trace", "Landing gear snag", "Engine vibration fix"],
    "Inspection":  ["Pre-flight walkaround", "Borescope inspection", "NDT check", "Annual compliance check"],
    "Emergency":   ["AOG engine fault", "Emergency hydraulic failure", "Critical avionics failure", "Fire warning system fault"],
}

SLA_TARGETS = {
    "Critical": (4.0,  2.0),
    "High":     (24.0, 12.0),
    "Medium":   (72.0, 48.0),
    "Low":      (168.0, 120.0),
}

COST_DESCRIPTIONS = {
    "Parts":       ["Hydraulic seal kit", "Filter element", "Wiring harness", "Bearing assembly", "Actuator unit"],
    "Labour":      ["Technician hours", "Specialist call-out", "Overtime labour"],
    "Subcontract": ["OEM engineering visit", "Third-party NDT", "Avionics shop repair"],
}

# ─────────────────────────────────────────────
# 3. GENERATE DATA
# ─────────────────────────────────────────────

def gen_assets(n=30):
    rows = []
    for i in range(1, n + 1):
        atype = random.choice(ASSET_TYPES)
        mfr   = random.choice(MANUFACTURERS[atype])
        model = random.choice(MODELS[atype])
        rows.append((
            f"AST-{i:04d}",
            f"{mfr} {model} #{i:03d}",
            atype,
            random.choice(LOCATIONS),
            mfr,
            model,
            random.randint(2010, 2022),
            random.choices(["Active", "Inactive", "Under Maintenance"], weights=[70, 10, 20])[0],
        ))
    return rows

def gen_technicians(n=20):
    rows = []
    for i in range(1, n + 1):
        level = random.choice(SKILL_LEVELS)
        rows.append((
            f"TECH-{i:04d}",
            fake.name(),
            level,
            random.choice(SPECIALISATIONS),
            HOURLY_RATES[level] + random.uniform(-5, 10),
            1,
        ))
    return rows

def gen_work_orders(assets, technicians, n=500):
    rows = []
    base_date = datetime(2023, 1, 1)
    asset_ids = [a[0] for a in assets]
    tech_ids  = [t[0] for t in technicians]

    for i in range(1, n + 1):
        wo_type  = random.choices(WO_TYPES, weights=[35, 35, 20, 10])[0]
        priority = random.choices(PRIORITIES, weights=[10, 25, 40, 25])[0]
        status   = random.choices(STATUSES, weights=[10, 15, 70, 5])[0]

        created_at = base_date + timedelta(
            days=random.randint(0, 364),
            hours=random.randint(6, 20)
        )

        started_at = completed_at = None
        downtime_hours = None

        if status in ("In Progress", "Completed", "Cancelled"):
            started_at = created_at + timedelta(hours=random.uniform(0.5, 8))

        if status == "Completed":
            target_h = SLA_TARGETS[priority][0]
            # ~75% of WOs meet SLA
            if random.random() < 0.75:
                duration = random.uniform(target_h * 0.2, target_h * 0.95)
            else:
                duration = random.uniform(target_h * 1.0, target_h * 2.5)
            completed_at = started_at + timedelta(hours=duration)
            downtime_hours = round(random.uniform(0, duration * 0.8), 2)

        rows.append((
            f"WO-{i:05d}",
            random.choice(asset_ids),
            random.choice(tech_ids) if status != "Open" else None,
            wo_type,
            priority,
            status,
            random.choice(WO_DESCRIPTIONS[wo_type]),
            created_at.strftime("%Y-%m-%d %H:%M:%S"),
            started_at.strftime("%Y-%m-%d %H:%M:%S") if started_at else None,
            completed_at.strftime("%Y-%m-%d %H:%M:%S") if completed_at else None,
            downtime_hours,
            random.choice(FAILURE_CODES) if wo_type in ("Corrective", "Emergency") else None,
        ))
    return rows

def gen_costs(work_orders):
    rows = []
    for wo in work_orders:
        wo_id  = wo[0]
        status = wo[5]
        if status not in ("Completed", "In Progress"):
            continue
        # 1–3 cost lines per eligible WO
        for _ in range(random.randint(1, 3)):
            ctype = random.choices(
                ["Parts", "Labour", "Subcontract"], weights=[50, 40, 10]
            )[0]
            rows.append((
                wo_id,
                ctype,
                random.choice(COST_DESCRIPTIONS[ctype]),
                round(random.uniform(50, 4500) if ctype == "Parts"
                      else random.uniform(100, 2000) if ctype == "Labour"
                      else random.uniform(500, 8000), 2),
                "USD",
            ))
    return rows

# ─────────────────────────────────────────────
# 4. WRITE TO SQLITE
# ─────────────────────────────────────────────

def build_database():
    conn = sqlite3.connect(DB_PATH)
    cur  = conn.cursor()
    cur.executescript(SCHEMA)

    # SLA definitions
    for priority, (target, escalation) in SLA_TARGETS.items():
        cur.execute(
            "INSERT OR IGNORE INTO sla_definitions VALUES (?,?,?)",
            (priority, target, escalation)
        )

    assets      = gen_assets(30)
    technicians = gen_technicians(20)
    work_orders = gen_work_orders(assets, technicians, 500)
    costs       = gen_costs(work_orders)

    cur.executemany("INSERT OR IGNORE INTO assets VALUES (?,?,?,?,?,?,?,?)", assets)
    cur.executemany("INSERT OR IGNORE INTO technicians VALUES (?,?,?,?,?,?)", technicians)
    cur.executemany("INSERT OR IGNORE INTO work_orders VALUES (?,?,?,?,?,?,?,?,?,?,?,?)", work_orders)
    cur.executemany(
        "INSERT INTO work_order_costs (wo_id,cost_type,description,amount,currency) VALUES (?,?,?,?,?)",
        costs
    )

    conn.commit()

    # ── Summary ──────────────────────────────
    print("✅  Database built:", DB_PATH)
    for table in ["assets", "technicians", "sla_definitions", "work_orders", "work_order_costs"]:
        count = cur.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
        print(f"   {table:<22} {count:>5} rows")

    # Quick sanity checks
    print("\n── SLA compliance preview ──")
    cur.execute("""
        SELECT
            wo.priority,
            COUNT(*) AS total,
            SUM(CASE
                WHEN (julianday(wo.completed_at) - julianday(wo.created_at)) * 24
                     <= sla.target_hours THEN 1 ELSE 0
            END) AS met,
            ROUND(
                100.0 * SUM(CASE
                    WHEN (julianday(wo.completed_at) - julianday(wo.created_at)) * 24
                         <= sla.target_hours THEN 1 ELSE 0
                END) / COUNT(*), 1
            ) AS pct
        FROM work_orders wo
        JOIN sla_definitions sla ON wo.priority = sla.priority
        WHERE wo.status = 'Completed'
        GROUP BY wo.priority
        ORDER BY CASE wo.priority
            WHEN 'Critical' THEN 1 WHEN 'High' THEN 2
            WHEN 'Medium' THEN 3 ELSE 4 END
    """)
    print(f"   {'Priority':<10} {'Total':>6} {'Met SLA':>8} {'%':>6}")
    for row in cur.fetchall():
        print(f"   {row[0]:<10} {row[1]:>6} {row[2]:>8} {row[3]:>5}%")

    print("\n── Total cost by type ──")
    cur.execute("""
        SELECT cost_type, COUNT(*), ROUND(SUM(amount),2)
        FROM work_order_costs GROUP BY cost_type
    """)
    for row in cur.fetchall():
        print(f"   {row[0]:<14} {row[1]:>4} lines   ${row[2]:>10,.2f}")

    conn.close()

if __name__ == "__main__":
    build_database()

import sqlite3
conn = sqlite3.connect("/content/maintenance.db")
cur = conn.cursor()

# Get column names for work_orders
cur.execute("PRAGMA table_info(work_orders)")
print([row[1] for row in cur.fetchall()])

for table in ["assets", "technicians", "work_order_costs", "sla_definitions"]:
    cur.execute(f"PRAGMA table_info({table})")
    print(f"{table}: {[row[1] for row in cur.fetchall()]}")

"""# **Level 1 — Basic filters and aggregates**

Q1: How many work orders exist per status?
"""

import pandas as pd
import sqlite3

conn = sqlite3.connect("/content/maintenance.db")

query1 = """
SELECT
    status,
    COUNT(*) AS total_work_orders
FROM work_orders
GROUP BY status
ORDER BY total_work_orders DESC;
"""

pd.read_sql_query(query1, conn)

"""Q2: What is the total maintenance cost per cost type?"""

query2 = """
SELECT
    cost_type,
    COUNT(*)              AS line_items,
    ROUND(SUM(amount), 2) AS total_cost,
    ROUND(AVG(amount), 2) AS avg_cost
FROM work_order_costs
GROUP BY cost_type
ORDER BY total_cost DESC;
"""

pd.read_sql_query(query2, conn)

"""Q3: How many work orders per priority and type?"""

query3 = """
SELECT
    priority,
    wo_type,
    COUNT(*) AS total
FROM work_orders
GROUP BY priority, wo_type
ORDER BY
    CASE priority
        WHEN 'Critical' THEN 1 WHEN 'High' THEN 2
        WHEN 'Medium' THEN 3 ELSE 4
    END,
    wo_type;
"""

pd.read_sql_query(query3, conn)

"""Q4: Which assets have the most work orders?"""

query4 = """
SELECT
    a.asset_id,
    a.asset_name,
    a.asset_type,
    COUNT(wo.wo_id) AS total_wo
FROM assets a
LEFT JOIN work_orders wo ON a.asset_id = wo.asset_id
GROUP BY a.asset_id
ORDER BY total_wo DESC
LIMIT 10;
"""

pd.read_sql_query(query4, conn)

"""# **Level 2 — Joins, subqueries, conditional aggregation**

Q5: SLA compliance rate by priority
"""

query5= """
SELECT
    wo.priority,
    sla.target_hours,
    COUNT(*)                                           AS completed_total,
    SUM(CASE
        WHEN (julianday(wo.completed_at) - julianday(wo.created_at)) * 24
             <= sla.target_hours THEN 1 ELSE 0
    END)                                               AS met_sla,
    ROUND(100.0 * SUM(CASE
        WHEN (julianday(wo.completed_at) - julianday(wo.created_at)) * 24
             <= sla.target_hours THEN 1 ELSE 0
    END) / COUNT(*), 1)                                AS sla_pct
FROM work_orders wo
JOIN sla_definitions sla ON wo.priority = sla.priority
WHERE wo.status = 'Completed'
GROUP BY wo.priority
ORDER BY CASE wo.priority
    WHEN 'Critical' THEN 1 WHEN 'High' THEN 2
    WHEN 'Medium' THEN 3 ELSE 4 END;
    """
pd.read_sql_query(query5, conn)

"""Q6: Total cost per asset with asset details"""

query6="""
SELECT
    a.asset_id,
    a.asset_name,
    a.asset_type,
    a.location,
    COUNT(DISTINCT wo.wo_id)      AS total_wo,
    ROUND(SUM(wc.amount), 2)      AS total_cost,
    ROUND(AVG(wc.amount), 2)      AS avg_cost_per_line
FROM assets a
JOIN work_orders wo    ON a.asset_id = wo.asset_id
JOIN work_order_costs wc ON wo.wo_id = wc.wo_id
GROUP BY a.asset_id
ORDER BY total_cost DESC
LIMIT 10;
"""
pd.read_sql_query(query6,conn)

"""Q7: Technician workload and average resolution time"""

query7 = """
SELECT
    t.full_name,
    t.skill_level,
    t.specialisation,
    COUNT(wo.wo_id)                                              AS total_assigned,
    SUM(CASE WHEN wo.status = 'Completed' THEN 1 ELSE 0 END)    AS completed,
    ROUND(AVG(
        CASE WHEN wo.status = 'Completed'
        THEN (julianday(wo.completed_at) - julianday(wo.started_at)) * 24
        END), 2)                                                 AS avg_resolution_hrs
FROM technicians t
LEFT JOIN work_orders wo ON t.technician_id = wo.technician_id
GROUP BY t.technician_id
ORDER BY total_assigned DESC;
"""
pd.read_sql_query(query7,conn)

"""Q8: Work orders that breached SLA — with full details"""

query8= """
SELECT
    wo.wo_id,
    a.asset_name,
    wo.priority,
    wo.wo_type,
    sla.target_hours,
    ROUND((julianday(wo.completed_at) - julianday(wo.created_at)) * 24, 1) AS actual_hours,
    ROUND((julianday(wo.completed_at) - julianday(wo.created_at)) * 24
          - sla.target_hours, 1)                                            AS overrun_hours,
    t.full_name AS technician
FROM work_orders wo
JOIN assets a          ON wo.asset_id       = a.asset_id
JOIN sla_definitions sla ON wo.priority     = sla.priority
JOIN technicians t     ON wo.technician_id  = t.technician_id
WHERE wo.status = 'Completed'
  AND (julianday(wo.completed_at) - julianday(wo.created_at)) * 24 > sla.target_hours
ORDER BY overrun_hours DESC
LIMIT 15;
"""
pd.read_sql_query(query8,conn)

"""# **Level 3 — Window functions and CTEs**

Q9: Running total of costs per month
"""

query9="""
SELECT
    strftime('%Y-%m', wo.created_at)          AS month,
    ROUND(SUM(wc.amount), 2)                   AS monthly_cost,
    ROUND(SUM(SUM(wc.amount)) OVER (
        ORDER BY strftime('%Y-%m', wo.created_at)
    ), 2)                                      AS running_total
FROM work_orders wo
JOIN work_order_costs wc ON wo.wo_id = wc.wo_id
GROUP BY month
ORDER BY month;
"""
pd.read_sql_query(query9,conn)

"""Q10: Rank technicians by completed work orders within each skill level"""

query10="""
SELECT
    full_name,
    skill_level,
    specialisation,
    completed,
    RANK() OVER (
        PARTITION BY skill_level
        ORDER BY completed DESC
    ) AS rank_within_level
FROM (
    SELECT
        t.full_name,
        t.skill_level,
        t.specialisation,
        SUM(CASE WHEN wo.status = 'Completed' THEN 1 ELSE 0 END) AS completed
    FROM technicians t
    LEFT JOIN work_orders wo ON t.technician_id = wo.technician_id
    GROUP BY t.technician_id
) ranked
ORDER BY skill_level, rank_within_level;
"""
pd.read_sql_query(query10,conn)

"""Q11: Asset downtime analysis — total and average per asset type"""

query11="""
WITH downtime_summary AS (
    SELECT
        a.asset_type,
        a.asset_id,
        a.asset_name,
        ROUND(SUM(wo.downtime_hours), 2)  AS total_downtime,
        COUNT(wo.wo_id)                    AS wo_count
    FROM assets a
    JOIN work_orders wo ON a.asset_id = wo.asset_id
    WHERE wo.downtime_hours IS NOT NULL
    GROUP BY a.asset_id
)
SELECT
    asset_type,
    asset_id,
    asset_name,
    total_downtime,
    wo_count,
    ROUND(AVG(total_downtime) OVER (
        PARTITION BY asset_type
    ), 2)                                  AS avg_downtime_by_type,
    RANK() OVER (
        PARTITION BY asset_type
        ORDER BY total_downtime DESC
    )                                      AS rank_in_type
FROM downtime_summary
ORDER BY asset_type, rank_in_type;
"""
pd.read_sql_query(query11,conn)

"""Q12: Month-over-month work order completion trend"""

query12="""
WITH monthly AS (
    SELECT
        strftime('%Y-%m', completed_at) AS month,
        COUNT(*)                         AS completed_count
    FROM work_orders
    WHERE status = 'Completed'
      AND completed_at IS NOT NULL
    GROUP BY month
)
SELECT
    month,
    completed_count,
    LAG(completed_count) OVER (ORDER BY month)   AS prev_month,
    completed_count - LAG(completed_count) OVER (
        ORDER BY month
    )                                             AS mom_change,
    ROUND(100.0 * (completed_count - LAG(completed_count) OVER (ORDER BY month))
        / LAG(completed_count) OVER (ORDER BY month), 1) AS mom_pct_change
FROM monthly
ORDER BY month;
"""
pd.read_sql_query(query12,conn)

"what month had the biggest spike and whether you think that's real signal or random noise from the synthetic data."

query12_A= """
SELECT
    strftime('%Y-%m', completed_at) AS month,
    wo_type,
    COUNT(*) AS count
FROM work_orders
WHERE status = 'Completed'
  AND completed_at IS NOT NULL
  AND strftime('%Y-%m', completed_at) IN ('2023-08','2023-09','2023-10')
GROUP BY month, wo_type
ORDER BY month, count DESC;
"""
pd.read_sql_query(query12_A,conn)

# Run this in Colab
import pandas as pd
import sqlite3

conn = sqlite3.connect("/content/maintenance.db")

df = pd.read_sql_query("""
    SELECT
        strftime('%Y-%m', wo.created_at) AS month,
        ROUND(SUM(wc.amount), 2) AS monthly_cost
    FROM work_orders wo
    JOIN work_order_costs wc ON wo.wo_id = wc.wo_id
    GROUP BY month
    ORDER BY month
""", conn)

avg = df['monthly_cost'].mean()
target = round(avg * 0.90, 2)  #-- 10% reduction target"
print(f"Average monthly cost: ${avg:,.2f}")
print(f"10% reduction target: ${target:,.2f}")

query13 = """
SELECT
    wo.asset_id,
    a.asset_name,
    a.asset_type,
    ROUND(SUM(wo.downtime_hours), 2) AS total_downtime,
    COUNT(wo.wo_id) AS wo_count
FROM work_orders wo
JOIN assets a ON wo.asset_id = a.asset_id
WHERE strftime('%Y-%m', wo.created_at) = '2023-07'
AND wo.downtime_hours IS NOT NULL
GROUP BY wo.asset_id
ORDER BY total_downtime DESC
LIMIT 10;
"""
pd.read_sql_query(query13,conn)

